--------------------------------------------------------
-- Archivo creado  - martes-julio-21-2020   
--------------------------------------------------------
REM INSERTING into EXFINAL.RESPUESTAS
SET DEFINE OFF;
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA11','A1','T01','R2','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA12','A1','T01','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA13','A1','T01','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA14','A1','T01','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA15','A1','T01','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA16','A1','T01','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA17','A1','T01','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA18','A1','T01','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA19','A1','T01','R4','0');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA110','A1','T01','R4','0');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA21','A2','T01','R4','0');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA22','A2','T01','R2','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA23','A2','T01','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA24','A2','T01','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA25','A2','T01','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA26','A2','T01','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA27','A2','T01','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA28','A2','T01','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA29','A2','T01','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA210','A2','T01','R4','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA31','A3','T02','R2','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA32','A3','T02','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA33','A3','T02','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA34','A3','T02','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA35','A3','T02','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA36','A3','T02','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA37','A3','T02','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA38','A3','T02','R3','50');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA39','A3','T02','R4','0');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA310','A3','T02','R4','0');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA41','A4','T02','R4','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA42','A4','T02','R2','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA43','A4','T02','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA44','A4','T02','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA45','A4','T02','R3','50');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA46','A4','T02','R3','100');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA47','A4','T02','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA48','A4','T02','R3','-25');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA49','A4','T02','R3','0');
Insert into EXFINAL.RESPUESTAS (ID_RESP,ID_ALUM,ID_TEST,RESP,PUNTAJE) values ('RESA410','A4','T02','R4','0');
